version: '3'
services:

  # SQL база для социальной сети
  sn.db.mysql:
    container_name: sn.db.mysql
    ports:
      - '3306:3306'
    image: mysql
    env_file:
      - .env

  # InMemory Data Base - будет использоваться для кеширования и для сохранения заданий в очереди
  sn.db.redis:
    container_name: sn.db.redis
    image: redis
    ports:
      - '6379:6379'

  # Внешний вид социальной сети
  sn.front.public:
    build: ./frontend/public
    volumes:
      - './frontend/public/src:/app'

  # Админка социальной сети
  sn.front.admin:
    build: ./frontend/admin
    volumes:
      - './frontend/admin/src:/app'

  # Микросервис api
  sn.api:
    build: ./backend/api
    volumes:
      - './backend/api/src:/app'
    depends_on:
      - sn.db.mysql
      - sn.db.redis

  # Nginx маршрутизатор
  sn.ngnix.router:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
    depends_on:
      - sn.api
      - sn.front.admin
      - sn.front.public



